environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

image: Visual Studio 2017

build_script:
  - gradlew assemble --info --stacktrace --no-daemon

#platform:
#  - x86
#  - x64

cache:
  - C:\Users\appveyor\.gradle
#

test_script:
  - gradlew test --info --stacktrace --no-daemon

before_build:
  - set Path=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%Path%
#

artifacts:
  - path: 'core\build\libs\*.jar'
    name: jimgui-core
  - path: 'kotlin-dsl\build\libs\*.jar'
    name: jimgui-dsl
#
